services:
  - type: web
    name: advent-calendar
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"

    envVars:
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromSecret: DATABASE_URL  # ← теперь это secret, а не fromDatabase
